print ("1. checking version") 
import sys
print (sys.version)
print ("2. simple operations")
print (3 + 4)
print (3 - 4)
print (3 * 4)
print (3 / 4)
print (3 % 4)
print (3 ** 4)
print (3 // 4)
print ("3. writing strings")
print ("Sofia")
print ("Muruve")
print ("Canada")
print ("I am enjoying 30 days of python")
print ("4. checking data types")
print (type (10))
print (type (9.8))
print (type (3.14))
print (type (4 - 4j))
print (type (['sofia', 'python', 'canada']))
print (type ("Muruve"))
